modLoader = "kotlinforforge"
loaderVersion = "[3,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "warehouse"
version = "${version}"
displayName = "Warehouse"
authors = "TechTastic"
description = '''
A Low-Tech Mass Storage System!
'''
#logoFile = ""

[[dependencies.warehouse]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.warehouse]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.warehouse]]
modId = "architectury"
mandatory = true
versionRange = "[4.11.93,)"
ordering = "AFTER"
side = "BOTH"